### ISSUE TITLE
Support for custom dataset

### ISSUE THREAD

**Issue by benedictflorance** [facebookresearch/suncet#14]
Does the repo have support for custom datasets? (Other than ImageNet/CIFAR10)

**Comment by MidoAssran** [comment]
Hi @benedictflorance,

To use a different dataset, you would just need to replace the [init_data()](https://github.com/facebookresearch/suncet/blob/master/src/paws_train.py#L197-L215) function call in `paws_train.py` to return your custom dataloader/samplers instead.

Happy to help you debug if you run into any issues here.
