### ISSUE TITLE
Mismatch in metrics for UDA method

### ISSUE THREAD

**Issue by klnavaneet** [facebookresearch/suncet#28]
There seems to be a mismatch in the accuracy and number of training epochs reported for the UDA method in table 1 of the PAWS paper. According to PAWS, on the 10% imagenet setting, UDA has an accuracy of 68.1% with 800 epochs of training. However, in table 5 of the UDA paper (https://arxiv.org/pdf/1904.12848.pdf), the accuracy is reported to be 68.78. Also, in page-20 of UDA, the training is said to be performed with bs=15360 for 40,000 steps. This approximately is (15360 * 40000) / 1281167 = 480 epochs. Am I missing something here or are the PAWS reported numbers wrong?

**Comment by MidoAssran** [comment]
Hi @klnavaneet this particular result refers to UDA with a batch-size of 2048 trained for 500,000 steps with an additional 5000 steps of warmup. Specifically, this result is from the more recent paper (https://arxiv.org/pdf/2003.10580.pdf) written by many of the same authors as the older UDA paper (Zihang Dai, Qizhe Xie, Minh-Thang Luong, Quoc V. Le).

I personally didn't notice this difference, but will make it clear in the next revision that this is the UDA number from the more recent MPL paper (by Hieu Pham, Zihang Dai, Qizhe Xie, Minh-Thang Luong, Quoc V. Le), and will also include the large-batch UDA result you mention.

**Comment by klnavaneet** [comment]
Great, thanks!
