### ISSUE TITLE
running fine tuning on a custom dataset

### ISSUE THREAD

**Issue by amandalucasp** [facebookresearch/suncet#29]
Hello, congratulations on your work and thanks for sharing your code. 
I'm currently trying to run fine-tuning using a single GPU and a custom dataset (around 3k samples), but I keep getting CUDA out of memory error. Is there any parameter I can adjust for the code to require less memory?

Thanks!

**Comment by amandalucasp** [comment]
I was able to successfully run fine-tuning after a few modifications in the code to fit my dataset, and also decreasing batch_size.

**Comment by uthillaivasan** [comment]
Hi Amanda, can you share how more about the way you set up your train/val data as well as what code modifications you focused on for a custom dataset? I'm trying to do this using the CUB-200-2011 (birds) dataset.

**Comment by amandalucasp** [comment]
Hi @uthillaivasan :) I implemented a custom pytorch dataset class to be able to load my data as it is on [the docs](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html). That way, I was able to re-use some classes implemented by the authors. Also, in my case, I'm dealing with a multi-label dataset, so I had to make adjustments to the loss functions etc. Currently I am able to successfully run the supervised fine-tuning proposed by the authors with these changes I mentioned; but I am still working on properly adjusting the code to run the pre-training step. Do you plan to run pre-training or fine-tuning? 

In case of running the pre-training, I believe we have to also implement a new sampler for the support set, as recommended by the author in https://github.com/facebookresearch/suncet/issues/19#issuecomment-900403043. I'm still working on this, but will be glad to share what changes were necessary once I'm done :)
