### ISSUE TITLE
Do you have any slides or video for this paper

### ISSUE THREAD

**Issue by wzn123** [facebookresearch/suncet#30]
Hello, I am a current PhD student who is very interested in your work. I see that this paper is accepted by ICCV2021 as an oral paper. I am wondering do you have the poster or slides or video presentation of this paper. I really want to share them with my classmates and students in my tutorial. Thanks in advance.

**Comment by MidoAssran** [comment]
Hi @wzn123,

Yes absolutely. The paper was presented as an Oral at ICCV'21, but unfortunately the video on their website can't be accessed without a registration. I had given a talk on PAWS to the Computer Vision Talks group, and that video is available online [here](https://www.youtube.com/watch?v=0BCb-TsMjXU).

The paper was also featured in the ICCV Daily magazine, so if your classmates and students are interested in a casual 2min read, they can find the link [here](https://www.rsipvision.com/ICCV2021-Friday/8/).

Hope this helps!

**Comment by wzn123** [comment]
Thanks for your reply and comments. Those posters and videos are very helpful for us. Your ideas really inspire us a lot. Hope you have a nice day!!
