### ISSUE TITLE
Requirement to run Single-GPU training 

### ISSUE THREAD

**Issue by 3bao** [facebookresearch/suncet#31]
What is the minimum GPU requirement to run the Single-GPU training? Thanks!

**Comment by MidoAssran** [comment]
Hi @3bao,

Assuming you've already cloned the repo and installed the following packages:
* Python 3.8
* PyTorch install 1.7.1
* torchvision
* CUDA 11.0
* Apex with CUDA extension
* Other dependencies: PyYaml, numpy, opencv, submitit

After that you can just follow the instructions [here](https://github.com/facebookresearch/suncet#single-gpu-training)
In short, you just need to
* download CIFAR10 to the appropriate path
* create a config file and save it in the `configs/paws/` directory
* run the command
```
python main.py
  --sel paws_train
  --fname configs/paws/3bao_config_file.yaml
  ```

You can see an example config file for single-GPU training on CIFAR10 [here](https://github.com/facebookresearch/suncet/blob/main/configs/paws/cifar10_train.yaml)
