### ISSUE TITLE
Ablation w/o multi crop?

### ISSUE THREAD

**Issue by LeeDoYup** [facebookresearch/suncet#4]
Hello. Thanks for the awesome project !
I wonder that how the multi-crop augmentations are important for the SSL performance.
Is there any results of ablation study, where the training does not contain multi-crop strategy?

**Comment by MidoAssran** [comment]
Hello @LeeDoYup,

We consider multi-crop an essential part of PAWS (i.e., mapping local features to global features) so we didn't experiment without using it, but if it's something you're interested in exploring I'm happy to help reviewing code/configs, or discussing results. I would expect that many of the hyper-parameters will need to be re-tuned to get the best performance possible without multi-crop.
