### ISSUE TITLE
Version of CIFAR to run the example

### ISSUE THREAD

**Issue by Aivan2008** [facebookresearch/suncet#7]
I cloned the code and tried to run it, but now the issue is - which version of CIFAR10 are you use in example? No data was downloaded automatically by the code. No python neither matlab or C++ version from official cite seems to be suitable for paths presented in the config file. Thank you for your answer.

**Comment by MidoAssran** [comment]
Hi, we use the default python version (which is the same as `torchvision.CIFAR10`).

In the config:
- `root_path` is your datasets directory, where you put all your data
- `image_folder` is the folder inside datasets, where `cifar-10-batches-py` exists (`cifar-10-batches-py` is the folder `torchvision.CIFAR10` looks for as well)

Here is an example to fix your issue. First download the python version you mentioned, an unzip, you will get a `cifar-10-batches-py` directory.
 Then create the following directory structure:
|- datasets/ 
|-- cifar10-data/
|---- cifar-10-batches-py/

In your config specify:
`root_path: datasets/`
`image_folder: cifar10-data`

I will update the README and configs to make this more clear.

**Comment by jmarrietar** [comment]
I assume the python version was `3.8` since there are some operators as `return *[self.dataset.transform(img) for _ in range(self.supervised_views)], target` that are invalid in python `3.7` (The one that Google Colab uses)
